import type { Metadata } from "next";
import "./globals.css";
import GlobalDataGuard from "@/components/layout/GlobalDataGuard";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Providers } from "./providers";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <GlobalDataGuard>{children}</GlobalDataGuard>
        </Providers>
      </body>
    </html>
  );
}
